HTML/CSS & JavaScript capstone project - Conference page
omarbabou/taste-food-capstone pull request #1
Opened 2022-06-06 18:47 UTC by omarbabou

Hello Reviewer ✋ 
### Project description
> In this capstone project (([remember what they are?](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/capstone_intro.md)) ) I have built the project based on an online website for a conference. Microverse provided some design guidelines for us to create the website, but I personalized the content, i.e., instead of a conference I have built `TASTE FOOD` website for showing meals  or for a web development course. I personalized my project so that people can see somthing unique in my portfolio to share with potential employers during job searching.

### Prjoject Geral Requirements
- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
### Tasks Implemented
> I have personalized the content of my page by choosing a `TASTE FOOD` topic that is different than the one in the original design.
> I have followed these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:
Colors.
> Typography: font face, size and weight.
Layout: composition and space between elements.
The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.

#### Pages built :

1. The home page.
2. The about page.
Each of these pages should have versions for 2 different screen sizes:

Mobile: up to 768px wide.
Desktop: 768px or wider.
Interactions

#### Links
- The home page should have a link in the menu to the about page.
- The logo in the header links to the home page.
Mobile menu
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
- The mobile menu should have a close (X) button that closes the menu.

#### Dynamic page
The section "Featured speakers" should be created dynamically in JavaScript.
You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.
Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

2022-06-07 09:14 UTC, Davidosky007 requested changes
Hi @omarbabou , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* Kindly provide a link to a recorded video presenting the features of your project
*  The maximum length of the video is 5 minutes.
* The video contains a clear and objective description about the project in professional English. * The topic and purpose of the project are made clear.
* The video contains a demo of the project, showing the pages in different screen sizes.
* The video contains a highlight about a piece of the code the student finds interesting or is proud of making
## _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 09:14 UTC, Davidosky007 commented on README.md
> +[Live Demo Link]()
* Kindly deploy your project using Github pages and update your readme file with the link

2022-06-07 09:14 UTC, Davidosky007 commented on README.md
> +### Setup
* Please add proper setup instructions to your readme file so that visitors to your repository can successfully set up your app locally

2022-06-07 09:14 UTC, Davidosky007 commented on about.html
> +        </div>
* Kindly fix the horizontal scroll bar on the mobile version navbar and menu drop down as it doesn't give a good user experience, users have to scroll left or right to properly navigate your pages. Below ⬇️ are screenshots of the pages 
![image](https://user-images.githubusercontent.com/52497246/172323006-9960dbc8-ff21-4541-a732-914870c53995.png)
![image](https://user-images.githubusercontent.com/52497246/172323042-26ecef66-c0d3-4610-b528-598aabf44cc7.png)

2022-06-07 09:14 UTC, Davidosky007 commented on about.html
> +        <div class="icons">
* Your design is missing the top dark bar with links and social icons and also nav link button interactions as you can see in the screenshot i have highlighted sections that needs fixing ( when a link is clicked and active the colour changes from the rest ),  Please 🙏 fix them so that your design matches the given template 
![image](https://user-images.githubusercontent.com/52497246/172325242-907260d0-016a-4d27-926b-5914234276c0.png)

2022-06-07 09:14 UTC, Davidosky007 commented on about.html
> +    </footer>
* I think the About page has a dark background as given in the original design, but yours has a white background footer, Kindly fix this 🙏 
![image](https://user-images.githubusercontent.com/52497246/172326710-3cc8b612-219b-49d1-9029-c10f073e50b6.png)

2022-06-07 09:14 UTC, Davidosky007 commented on index.html
> +            <p>
* Please work on the home page middle section as it has a big margin on the right and a horizontal scroll bar below. i have attached a screenshot highlighting the part that needs fixing 
![image](https://user-images.githubusercontent.com/52497246/172327777-7553d9e2-9964-43ee-be8e-4e38c06790b5.png)

2022-06-07 09:14 UTC, Davidosky007 commented on index.html
> +        <h3 class="third-title">Our Services</h3>
Kindly fix this section of your home page for both mobile and desktop versions as it doesn't match the original design given 
## Original design 
![image](https://user-images.githubusercontent.com/52497246/172330810-15ce8f00-4b66-45e4-9b60-636e273ab531.png)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------## Yours 
![image](https://user-images.githubusercontent.com/52497246/172330902-824af312-525c-4c56-a860-cb1384870d56.png)
## Mobile version Yours 
![image](https://user-images.githubusercontent.com/52497246/172334188-8108509b-6dda-48ad-ae0e-fd7abd961201.png)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------## Original
![image](https://user-images.githubusercontent.com/52497246/172334482-15f7e436-edde-4765-a7b5-fa296fc2b640.png)

2022-06-07 09:14 UTC, Davidosky007 commented on index.html
> +      </section>
* This section is missing the red divider from the original design, Please note that it is important your design matches the given template as this would help you in your future job as a developer
*## Original design 
![image](https://user-images.githubusercontent.com/52497246/172333567-f87f0ec0-c94f-4222-9412-f6d01bd45c0d.png)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------## Yours 
![image](https://user-images.githubusercontent.com/52497246/172333722-2f1826f3-cd94-4d70-9131-abb472126095.png)

2022-06-07 09:14 UTC, Davidosky007 commented on script/app.js
> +}); */
* Kindly remove all commented code from your project as it makes your codebase bulky and unprofesional

2022-06-07 09:14 UTC, Davidosky007 commented on about.html
> +    </section>
* Kindly work on this section of your about page desktop version and mobile version as it doesn't match the given design, below ⬇️ is are scrrenshots of the section missing 
* ## Original design desktop
![image](https://user-images.githubusercontent.com/52497246/172336969-b61425d0-d6fc-4ae4-bf5f-6e3e6713f155.png)
## Original design mobile 
![image](https://user-images.githubusercontent.com/52497246/172337894-b9f186d5-7526-4817-84d3-097ecceb1657.png)

2022-06-07 09:14 UTC, Davidosky007 commented on css/desktop.css
> +  }
Kindly make sure all your pages use the exact same colours and font family, for text, backgrounds, borders, etc, from the original design 
* Basic color from design: #272A31, #EC5242, #D3D3D3
* Fonts used originally: Cocogoose, Lato
Please work on these highlighted issues

2022-06-08 12:07 UTC, mke2111 commented
Project Under Review.
Kindly wait for a response. 😄

2022-06-08 12:08 UTC, mke2111 commented on about.html
> +        </div>
Resolved 👍🏽

2022-06-08 12:12 UTC, mke2111 commented on about.html
> +        <div class="icons">
Resolved 👍🏽 

This does not apply to your page entirely so we can consider it resolved.

2022-06-08 12:12 UTC, mke2111 commented on about.html
> +    </footer>
Resolved 👍🏽

2022-06-08 12:20 UTC, mke2111 commented on index.html
> +        <h3 class="third-title">Our Services</h3>
Resolved 👍🏽

2022-06-08 12:21 UTC, mke2111 commented on index.html
> +      </section>
Resolved 👍🏽

2022-06-08 12:22 UTC, mke2111 commented on script/app.js
> +}); */
Cleared 👍🏽

2022-06-08 12:24 UTC, mke2111 commented on about.html
> +    </section>
Resolved 👍🏽

2022-06-08 12:27 UTC, mke2111 commented on css/desktop.css
> +  }
Resolved 👍🏽

2022-06-08 12:28 UTC, mke2111 commented on index.html
> +            <p>
Not yet resolved.

2022-06-08 12:33 UTC, mke2111 requested changes
### Hey @omarbabou, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 12:36 UTC, mke2111 commented on css/desktop.css
> +  }
As previously requested.

The homepage - desktop version still has a horizontal scroll between widths of `768px - 1098px`.

Give this a fix just like you did with the about page.

2022-06-29 11:39 UTC, merged